### ISSUE TITLE
[Enhancement] Small suggestions for faster reading

### ISSUE THREAD

**Issue by nicolas-raoul** [nbeaver/try-decodings#1]
Great program, I just feel the reading speed could be improved a little bit by:
- Aligning the strings
- Putting all failed encoding at the end
- Removing the `b''` part

Example:

```
Base64 :                Hi Tomas!
Ascii85 :               \x9c\xfeA\xadw%\xd1\xc8\x8b
Base85 :                W\xb9\x92{2"\xbd\x0fF
ROT13 :                 FTxtIT9gLKZu
MIME quoted-printable : SGkgVG9tYXMh
Percent-encoding :      SGkgVG9tYXMh
Base32 failed.
Base16 failed.
Uuencoding failed.
BinHex failed.
```

This will be especially important when many more encodings are implemented.

Cheers! :-)

**Comment by nbeaver** [comment]
Good suggestions! I particularly agree with the first two.

The `b''` part is how python3 represents bytes before they become strings, so it provides potentially useful information, particularly for representing Unicode. Currently the script tries to decode the bytes into Unicode using the default encoding, and displays bytes if that fails. I agree that this is less than clear, though.

Here's an example to show what I mean:

```
$ printf '(R₁² + R₁ R₂ + R₂²)' | base64 | try_decodings.py
Base64 : (R₁² + R₁ R₂ + R₂²)
Base32 failed.
Base16 failed.
Ascii85 : b'\x84\rS\x0c\xf4!\xbf\x1df\x8c\x14y\xe2\x9d\xec.\xa4\xe2\xc6\xa2\xe1:*\xde\x88t\xce\nl\xd2\x10"'
Base85 failed with ValueError.
Uuencoding failed.
BinHex failed.
ROT13 : XSYvtbUPfvNeVSYvtbRtHhXPtvNeVSYvtbYPfvx=

MIME quoted-printable : KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik
Percent-encoding : KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik=

HTML : KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik=
```

So if there is a `b''` in the output, it means that the decoding was successful, but the result is not valid Unicode, at least with the default encoding.

If it didn't try to decode the Unicode, it would look like this:

```
$ printf '(R₁² + R₁ R₂ + R₂²)' | base64 | try_decodings.py
Base64 : b'(R\xe2\x82\x81\xc2\xb2 + R\xe2\x82\x81 R\xe2\x82\x82 + R\xe2\x82\x82\xc2\xb2)'
Base32 failed.
Base16 failed.
Ascii85 : b'\x84\rS\x0c\xf4!\xbf\x1df\x8c\x14y\xe2\x9d\xec.\xa4\xe2\xc6\xa2\xe1:*\xde\x88t\xce\nl\xd2\x10"'
Base85 failed with ValueError.
Uuencoding failed.
BinHex failed.
ROT13 : b'XSYvtbUPfvNeVSYvtbRtHhXPtvNeVSYvtbYPfvx=\n'
MIME quoted-printable : b'KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik'
Percent-encoding : b'KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik=\n'
HTML : b'KFLigoHCsiArIFLigoEgUuKCgiArIFLigoLCsik=\n'
```

 Do you think the current behavior makes sense, or is it more confusing than leaving everything as raw bytes?

**Comment by nbeaver** [comment]
First two are done. https://github.com/nbeaver/try-decodings/commit/95a3e14d347273ab8f6f9cec61eff7e3d7a4afd6 https://github.com/nbeaver/try-decodings/commit/95dc7a92191198e928998a95fd6e57c726755ec8

**Comment by nicolas-raoul** [comment]
Thanks, wonderful :-)

**Comment by nbeaver** [comment]
Are you ok with leaving the `b''`?

**Comment by nicolas-raoul** [comment]
It seemed superfluous to me, but since you probably know Python better than me, I let you decide :-)

**Comment by nbeaver** [comment]
Good, I'll close it. It's the easiest way to represent raw bytes when the encoding is unknown.

Relevant documentation is here if you're curious: https://docs.python.org/3/reference/lexical_analysis.html#strings
