### ISSUE TITLE
[Enhancement] Do not display lines where output=input

### ISSUE THREAD

**Issue by nicolas-raoul** [nbeaver/try-decodings#2]
Idea from http://softwarerecs.stackexchange.com/questions/18615 :

> Might want to include a test so that if a given encoding spits out unchanged text, it's suppressed.

Indeed it makes human visual detection more efficient.

**Comment by nbeaver** [comment]
Done.

**Comment by nbeaver** [comment]
Done. https://github.com/nbeaver/try-decodings/commit/0cd719df2f76aa62928b6fad5a3be35227eb6d0c
